import type { Recipe, RecipeMeta, RecipeSource, RegistryConfig, DiscoverResponse } from '@awi-protocol/types';
import type { DBAdapter } from './db';
import { PolicyEnforcer, CapabilityManager } from './security';
import { DOMExtractor } from './extractor';
import { hashRecipe } from './db';

export class GitRecipeSource implements RecipeSource {
  name = 'git-curated';
  priority = 1;

  constructor(
    private repoURL: string,
    _branch: string = 'main'
  ) {}

  async fetch(domain: string, action: string, version: string): Promise<Recipe | null> {
    const path = `${this.repoURL}/${domain}/${action}/${version}.json`;
    try {
      const res = await fetch(path, { signal: AbortSignal.timeout(5000) });
      if (!res.ok) return null;
      const recipe: Recipe = await res.json();
      return recipe;
    } catch {
      return null;
    }
  }

  async list(_domain?: string): Promise<RecipeMeta[]> {
    return [];
  }
}

export class LocalDBSource implements RecipeSource {
  name = 'local-db';
  priority = 2;

  constructor(private db: DBAdapter) {}

  async fetch(domain: string, action: string, version: string): Promise<Recipe | null> {
    const recipes = await this.db.listRecipes(domain);
    const meta = recipes.find(r => r.action === action && r.version === version);
    if (!meta) return null;
    return this.db.getRecipe(meta.hash);
  }

  async list(domain?: string): Promise<RecipeMeta[]> {
    return this.db.listRecipes(domain);
  }
}

export class SeedSource implements RecipeSource {
  name = 'seed-bundled';
  priority = 0;

  constructor(private seeds: Map<string, Recipe>) {}

  async fetch(domain: string, action: string, version: string): Promise<Recipe | null> {
    const key = `${domain}/${action}/${version}`;
    return this.seeds.get(key) || null;
  }

  async list(domain?: string): Promise<RecipeMeta[]> {
    const metas: RecipeMeta[] = [];
    for (const [key, recipe] of this.seeds) {
      if (!domain || key.startsWith(domain + '/')) {
        metas.push(recipe.meta);
      }
    }
    return metas;
  }
}

export class AutoDiscoverSource implements RecipeSource {
  name = 'auto-discover';
  priority = 99;

  constructor(private extractor: DOMExtractor) {}

  async fetch(_domain: string, _action: string, _version: string): Promise<Recipe | null> {
    return null;
  }

  async generate(url: string, goal?: string): Promise<Recipe> {
    const discovery = await this.extractor.discover(url, goal);
    const steps = discovery.action_plan || this.inferSteps(discovery);

    const recipe: Recipe = {
      meta: {
        domain: new URL(url).hostname,
        action: goal || 'inspect',
        version: 'auto',
        hash: '',
        trustScore: 0.0,
        permissions: ['read:public'],
        jsRequired: true,
        authRequired: discovery.risks.some(r => r.risk_type === 'auth_required'),
        rateLimitTag: new URL(url).hostname,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        author: 'auto-discover',
        tags: ['auto-generated'],
      },
      steps,
    };

    recipe.meta.hash = hashRecipe(recipe);
    return recipe;
  }

  private inferSteps(discovery: DiscoverResponse): any[] {
    return (discovery.interactive_elements || []).map((el, i) => ({
      step_number: i + 1,
      action: el.element_type === 'search' ? 'type' : 'click',
      target: el.how_to_target || el.selector_hint || `*[data-awi-id="${el.element_id}"]`,
      reason: el.purpose,
      optional: true,
    }));
  }
}

export class RecipeRegistry {
  private sources: RecipeSource[];
  private db: DBAdapter;
  private policy: PolicyEnforcer;
  private caps: CapabilityManager;
  private autoDiscover: AutoDiscoverSource | null;

  constructor(
    config: RegistryConfig,
    db: DBAdapter,
    policy: PolicyEnforcer,
    caps: CapabilityManager,
    autoDiscover?: AutoDiscoverSource
  ) {
    this.sources = [...config.sources].sort((a, b) => a.priority - b.priority);
    this.db = db;
    this.policy = policy;
    this.caps = caps;
    this.autoDiscover = autoDiscover || null;
  }

  async resolve(uri: string): Promise<Recipe> {
    const parsed = this.parseURI(uri);
    if (!parsed) throw new Error(`Invalid AWI URI: ${uri}`);
    const { domain, action, version } = parsed;

    for (const source of this.sources) {
      const recipe = await source.fetch(domain, action, version);
      if (recipe && this.validate(recipe)) {
        await this.db.putRecipe(recipe);
        return recipe;
      }
    }

    if (this.autoDiscover && this.policy.policy.allowAutoGenerated) {
      const url = `https://${domain}`;
      const recipe = await this.autoDiscover.generate(url, action);

      const policyCheck = this.policy.evaluate(recipe);
      if (!policyCheck.allowed) {
        throw new Error(`Auto-generated recipe blocked: ${policyCheck.reason}`);
      }

      await this.db.putRecipe(recipe);
      return recipe;
    }

    throw new Error(`Recipe not found: ${uri}`);
  }

  private validate(recipe: Recipe): boolean {
    const policyCheck = this.policy.evaluate(recipe);
    if (!policyCheck.allowed) return false;

    const capCheck = this.caps.checkRecipe(recipe);
    if (!capCheck.allowed) return false;

    return true;
  }

  parseURI(uri: string): { domain: string; action: string; version: string } | null {
    const match = uri.match(/^awi:\/\/([^\/]+)\/(.+)\/([^\/]+)$/);
    if (!match) return null;
    return { domain: match[1], action: match[2], version: match[3] };
  }

  async list(domain?: string): Promise<RecipeMeta[]> {
    const all: RecipeMeta[] = [];
    for (const source of this.sources) {
      if (source.list) {
        const metas = await source.list(domain);
        all.push(...metas);
      }
    }
    const byHash = new Map<string, RecipeMeta>();
    for (const meta of all) {
      const existing = byHash.get(meta.hash);
      if (!existing || meta.trustScore > existing.trustScore) {
        byHash.set(meta.hash, meta);
      }
    }
    return Array.from(byHash.values()).sort((a, b) => b.trustScore - a.trustScore);
  }
}
