import type { Recipe, Capability, SecurityPolicy } from '@awi-protocol/types';
import { createSign, createVerify } from 'crypto';
import { hashRecipe } from './db';

export class RecipeSigner {
  private privateKey: string;
  private publicKey: string;

  constructor(pemPrivateKey: string, pemPublicKey: string) {
    this.privateKey = pemPrivateKey;
    this.publicKey = pemPublicKey;
  }

  sign(recipe: Recipe): Recipe {
    const hash = hashRecipe(recipe);
    const signer = createSign('SHA256');
    signer.update(hash);
    const signature = signer.sign(this.privateKey, 'hex');

    return {
      ...recipe,
      meta: {
        ...recipe.meta,
        hash,
        signature,
        publicKey: this.publicKey,
      },
    };
  }

  static verify(recipe: Recipe): boolean {
    if (!recipe.meta.signature || !recipe.meta.publicKey) return false;
    const hash = hashRecipe(recipe);
    if (hash !== recipe.meta.hash) return false;

    const verifier = createVerify('SHA256');
    verifier.update(hash);
    return verifier.verify(recipe.meta.publicKey, recipe.meta.signature, 'hex');
  }
}

export class CapabilityManager {
  private caps: Map<string, Capability[]> = new Map();

  constructor(private sandboxPermissions: string[] = []) {}

  grant(domain: string, permission: string, ttlDays?: number): Capability {
    const cap: Capability = {
      domain,
      permission,
      grantedAt: new Date().toISOString(),
      expiresAt: ttlDays
        ? new Date(Date.now() + ttlDays * 86400000).toISOString()
        : undefined,
    };
    const key = `${domain}:${permission}`;
    const existing = this.caps.get(key) || [];
    this.caps.set(key, [...existing, cap]);
    return cap;
  }

  check(domain: string, permission: string): boolean {
    if (this.sandboxPermissions.includes(permission)) return true;
    const key = `${domain}:${permission}`;
    const caps = this.caps.get(key) || [];
    const now = new Date().toISOString();
    return caps.some(c => !c.expiresAt || c.expiresAt > now);
  }

  checkRecipe(recipe: Recipe): { allowed: boolean; missing: string[] } {
    const missing: string[] = [];
    for (const perm of recipe.meta.permissions) {
      if (!this.check(recipe.meta.domain, perm)) {
        missing.push(perm);
      }
    }
    return { allowed: missing.length === 0, missing };
  }

  revoke(domain: string, permission: string): void {
    this.caps.delete(`${domain}:${permission}`);
  }
}

export class PolicyEnforcer {
  constructor(public policy: SecurityPolicy) {}

  getSandboxPermissions(): string[] {
    return this.policy.sandboxPermissions;
  }

  evaluate(recipe: Recipe): { allowed: boolean; reason?: string } {
    const meta = recipe.meta;

    if (this.policy.blockedDomains.includes(meta.domain)) {
      return { allowed: false, reason: `Domain ${meta.domain} is blacklisted` };
    }
    if (this.policy.allowedDomains.length > 0 && !this.policy.allowedDomains.includes(meta.domain)) {
      return { allowed: false, reason: `Domain ${meta.domain} not in whitelist` };
    }

    if (!meta.signature && !this.policy.allowUnsignedRecipes) {
      return { allowed: false, reason: 'Unsigned recipes disabled by policy' };
    }

    if (meta.trustScore === 0 && !this.policy.allowAutoGenerated) {
      return { allowed: false, reason: 'Auto-generated recipes disabled by policy' };
    }

    if (meta.trustScore < this.policy.maxTrustThreshold) {
      return { allowed: false, reason: `Trust score ${meta.trustScore} below threshold ${this.policy.maxTrustThreshold}` };
    }

    return { allowed: true };
  }
}

interface RateLimitState {
  tokens: number;
  lastRefill: number;
}

export class LocalRateLimiter {
  private limits: Map<string, { rpm: number; burst: number }> = new Map();
  private states: Map<string, RateLimitState> = new Map();

  configure(domain: string, requestsPerMinute: number, burst: number) {
    this.limits.set(domain, { rpm: requestsPerMinute, burst });
  }

  async acquire(domain: string): Promise<boolean> {
    const limit = this.limits.get(domain);
    if (!limit) return true;

    const now = Date.now();
    const key = domain;
    let state = this.states.get(key);

    if (!state) {
      state = { tokens: limit.burst, lastRefill: now };
    }

    const elapsedMs = now - state.lastRefill;
    const refillRate = limit.rpm / 60000;
    const tokensToAdd = elapsedMs * refillRate;
    state.tokens = Math.min(limit.burst, state.tokens + tokensToAdd);
    state.lastRefill = now;

    if (state.tokens >= 1) {
      state.tokens -= 1;
      this.states.set(key, state);
      return true;
    }

    return false;
  }

  async wait(domain: string): Promise<void> {
    while (!(await this.acquire(domain))) {
      await new Promise(r => setTimeout(r, 100));
    }
  }
}

export const DEFAULT_POLICY: SecurityPolicy = {
  allowUnsignedRecipes: true,
  allowAutoGenerated: true,
  maxTrustThreshold: 0.0,
  sandboxPermissions: ['read:public'],
  allowedDomains: [],
  blockedDomains: ['localhost', '127.0.0.1', '0.0.0.0'],
};

export const STRICT_POLICY: SecurityPolicy = {
  allowUnsignedRecipes: false,
  allowAutoGenerated: false,
  maxTrustThreshold: 0.8,
  sandboxPermissions: ['read:public'],
  allowedDomains: [],
  blockedDomains: [],
};
