import { describe, it, expect } from 'vitest';
import { RecipeRegistry, SeedSource, LocalDBSource } from '../src/registry';
import { FileSystemDB } from '../src/db';
import { PolicyEnforcer, CapabilityManager } from '../src/security';
import { SEED_RECIPES } from '../src/seeds';

describe('RecipeRegistry', () => {
  const db = new FileSystemDB('./.awi-test');
  const policy = new PolicyEnforcer({
    allowUnsignedRecipes: true,
    allowAutoGenerated: true,
    maxTrustThreshold: 0.0,
    sandboxPermissions: ['read:public'],
    allowedDomains: [],
    blockedDomains: [],
  });
  const caps = new CapabilityManager();
  caps.grant('github.com', 'read:public');

  it('should resolve seed recipes', async () => {
    const seeds = new SeedSource(SEED_RECIPES);
    const registry = new RecipeRegistry(
      { sources: [seeds], autoDiscover: false, cacheTtlMs: 60000, trustThreshold: 0.0 },
      db,
      policy,
      caps
    );

    const recipe = await registry.resolve('awi://github.com/repos/search/v1');
    expect(recipe.meta.domain).toBe('github.com');
    expect(recipe.steps.length).toBeGreaterThan(0);
  });

  it('should parse valid URIs', () => {
    const seeds = new SeedSource(SEED_RECIPES);
    const registry = new RecipeRegistry(
      { sources: [seeds], autoDiscover: false, cacheTtlMs: 60000, trustThreshold: 0.0 },
      db,
      policy,
      caps
    );

    const parsed = registry.parseURI('awi://github.com/repos/search/v1');
    expect(parsed).toEqual({ domain: 'github.com', action: 'repos/search', version: 'v1' });
  });

  it('should reject invalid URIs', () => {
    const seeds = new SeedSource(SEED_RECIPES);
    const registry = new RecipeRegistry(
      { sources: [seeds], autoDiscover: false, cacheTtlMs: 60000, trustThreshold: 0.0 },
      db,
      policy,
      caps
    );

    expect(registry.parseURI('not-a-uri')).toBeNull();
  });

  it('should cache resolved recipes in local DB', async () => {
    const seeds = new SeedSource(SEED_RECIPES);
    const registry = new RecipeRegistry(
      { sources: [seeds], autoDiscover: false, cacheTtlMs: 60000, trustThreshold: 0.0 },
      db,
      policy,
      caps
    );

    await registry.resolve('awi://github.com/repos/search/v1');
    const cached = await db.listRecipes('github.com');
    expect(cached.length).toBeGreaterThan(0);
    expect(cached[0].domain).toBe('github.com');
  });

  it('should deduplicate recipes by hash', async () => {
    const seeds = new SeedSource(SEED_RECIPES);
    const registry = new RecipeRegistry(
      { sources: [seeds], autoDiscover: false, cacheTtlMs: 60000, trustThreshold: 0.0 },
      db,
      policy,
      caps
    );

    const list = await registry.list('github.com');
    const hashes = list.map(r => r.hash);
    expect(new Set(hashes).size).toBe(hashes.length);
  });
});

describe('SeedSource', () => {
  it('should contain GitHub search recipe', () => {
    expect(SEED_RECIPES.has('github.com/repos/search/v1')).toBe(true);
  });

  it('should have valid hashes', () => {
    for (const [key, recipe] of SEED_RECIPES) {
      expect(recipe.meta.hash).toMatch(/^sha256:/);
      expect(recipe.meta.hash.length).toBe(71);
    }
  });
});
